-- Note: Table and index names use lowercase 'dhcplease' because MySQL/MariaDB
-- is case-sensitive on Linux (lower_case_table_names=0), and queries in
-- JdbcLeaseManager use lowercase table names.
CREATE TABLE dhcplease (
	IPADDRESS VARBINARY(16) PRIMARY KEY,
    DUID VARBINARY(130) NOT NULL,
    IATYPE SMALLINT,
    IAID BIGINT,
    PREFIXLEN SMALLINT,
	STATE SMALLINT,
	HAPEERSTATE SMALLINT,
    STARTTIME TIMESTAMP NULL,
    PREFERREDENDTIME TIMESTAMP NULL,
    VALIDENDTIME TIMESTAMP NULL,
    OPTIONS BLOB,
    IA_OPTIONS BLOB,
    IPADDR_OPTIONS BLOB
) ENGINE=InnoDB;
CREATE INDEX TUPLE_NDX ON dhcplease (DUID, IATYPE, IAID);
CREATE INDEX DUID_NDX ON dhcplease (DUID);
CREATE INDEX IATYPE_NDX ON dhcplease (IATYPE);
CREATE INDEX STATE_NDX ON dhcplease (STATE);
CREATE INDEX STARTTIME_NDX ON dhcplease (STARTTIME);
CREATE INDEX ENDTIME_NDX ON dhcplease (VALIDENDTIME);
