CREATE TABLE DHCPLEASE (
	IPADDRESS VARBINARY(16) PRIMARY KEY,
    DUID VARBINARY(130) NOT NULL,
    IATYPE SMALLINT,
    IAID BIGINT,
    PREFIXLEN SMALLINT,
	STATE SMALLINT,
	HAPEERSTATE SMALLINT,
    STARTTIME TIMESTAMP,
    PREFERREDENDTIME TIMESTAMP,
    VALIDENDTIME TIMESTAMP,
    OPTIONS BLOB,
    IA_OPTIONS BLOB,
    IPADDR_OPTIONS BLOB
);
CREATE INDEX TUPLE_NDX ON DHCPLEASE (DUID, IATYPE, IAID);
CREATE INDEX DUID_NDX ON DHCPLEASE (DUID);
CREATE INDEX IATYPE_NDX ON DHCPLEASE (IATYPE);
CREATE INDEX STATE_NDX ON DHCPLEASE (STATE);
CREATE INDEX STARTTIME_NDX ON DHCPLEASE (STARTTIME);
CREATE INDEX ENDTIME_NDX ON DHCPLEASE (VALIDENDTIME);
