CREATE TABLE DHCPLEASE (
	IPADDRESS VARCHAR(16) PRIMARY KEY,
    DUID VARCHAR(1024) NOT NULL,
    IATYPE SMALLINT,
    IAID BIGINT,
    PREFIXLEN SMALLINT,
	STATE SMALLINT,
    STARTTIME TIMESTAMP,
    PREFERREDENDTIME TIMESTAMP,
    VALIDENDTIME TIMESTAMP,
    IA_OPTIONS VARCHAR(32672),
    IPADDR_OPTIONS VARCHAR(32672)
);
CREATE INDEX TUPLE_NDX ON DHCPLEASE (DUID, IATYPE, IAID);
CREATE INDEX DUID_NDX ON DHCPLEASE (DUID);
CREATE INDEX IATYPE_NDX ON DHCPLEASE (IATYPE);
CREATE INDEX STATE_NDX ON DHCPLEASE (STATE);
CREATE INDEX ENDTIME_NDX ON DHCPLEASE (VALIDENDTIME);
