//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.2-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.03.16 at 08:14:09 PM EST 
//


package com.agr.dhcpv6.server.config.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="abcPolicy" type="{}abcPolicy"/>
 *         &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
 *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serverIdOption" type="{}serverIdOption"/>
 *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *         &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
 *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="filterGroups" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{}name"/>
 *                   &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
 *                   &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
 *                   &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
 *                   &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *                   &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *                   &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *                   &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *                   &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *                   &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
 *                   &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="links" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
 *                   &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
 *                   &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="serverIdOption" type="{}serverIdOption" minOccurs="0"/>
 *                   &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *                   &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *                   &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *                   &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *                   &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *                   &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
 *                   &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="filterGroups" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{}name"/>
 *                             &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
 *                             &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
 *                             &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
 *                             &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *                             &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *                             &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *                             &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *                             &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *                             &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
 *                             &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "abcPolicy",
    "xyzPolicy",
    "genericPolicies",
    "serverIdOption",
    "preferenceOption",
    "serverUnicastOption",
    "statusCodeOption",
    "vendorInfoOption",
    "dnsServersOption",
    "domainListOption",
    "genericOptions",
    "filterGroups",
    "links"
})
@XmlRootElement(name = "dhcpV6ServerConfig")
public class DhcpV6ServerConfig
    implements Serializable
{

    protected boolean abcPolicy;
    protected Integer xyzPolicy;
    protected List<Policy> genericPolicies;
    @XmlElement(required = true)
    protected ServerIdOption serverIdOption;
    protected PreferenceOption preferenceOption;
    protected ServerUnicastOption serverUnicastOption;
    protected StatusCodeOption statusCodeOption;
    protected VendorInfoOption vendorInfoOption;
    protected DnsServersOption dnsServersOption;
    protected DomainListOption domainListOption;
    protected List<Option> genericOptions;
    protected List<DhcpV6ServerConfig.FilterGroups> filterGroups;
    protected List<DhcpV6ServerConfig.Links> links;

    /**
     * Gets the value of the abcPolicy property.
     * 
     */
    public boolean isAbcPolicy() {
        return abcPolicy;
    }

    /**
     * Sets the value of the abcPolicy property.
     * 
     */
    public void setAbcPolicy(boolean value) {
        this.abcPolicy = value;
    }

    /**
     * Gets the value of the xyzPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXyzPolicy() {
        return xyzPolicy;
    }

    /**
     * Sets the value of the xyzPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXyzPolicy(Integer value) {
        this.xyzPolicy = value;
    }

    /**
     * Gets the value of the genericPolicies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericPolicies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Policy }
     * 
     * 
     */
    public List<Policy> getGenericPolicies() {
        if (genericPolicies == null) {
            genericPolicies = new ArrayList<Policy>();
        }
        return this.genericPolicies;
    }

    /**
     * Gets the value of the serverIdOption property.
     * 
     * @return
     *     possible object is
     *     {@link ServerIdOption }
     *     
     */
    public ServerIdOption getServerIdOption() {
        return serverIdOption;
    }

    /**
     * Sets the value of the serverIdOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerIdOption }
     *     
     */
    public void setServerIdOption(ServerIdOption value) {
        this.serverIdOption = value;
    }

    /**
     * Gets the value of the preferenceOption property.
     * 
     * @return
     *     possible object is
     *     {@link PreferenceOption }
     *     
     */
    public PreferenceOption getPreferenceOption() {
        return preferenceOption;
    }

    /**
     * Sets the value of the preferenceOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferenceOption }
     *     
     */
    public void setPreferenceOption(PreferenceOption value) {
        this.preferenceOption = value;
    }

    /**
     * Gets the value of the serverUnicastOption property.
     * 
     * @return
     *     possible object is
     *     {@link ServerUnicastOption }
     *     
     */
    public ServerUnicastOption getServerUnicastOption() {
        return serverUnicastOption;
    }

    /**
     * Sets the value of the serverUnicastOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerUnicastOption }
     *     
     */
    public void setServerUnicastOption(ServerUnicastOption value) {
        this.serverUnicastOption = value;
    }

    /**
     * Gets the value of the statusCodeOption property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodeOption }
     *     
     */
    public StatusCodeOption getStatusCodeOption() {
        return statusCodeOption;
    }

    /**
     * Sets the value of the statusCodeOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodeOption }
     *     
     */
    public void setStatusCodeOption(StatusCodeOption value) {
        this.statusCodeOption = value;
    }

    /**
     * Gets the value of the vendorInfoOption property.
     * 
     * @return
     *     possible object is
     *     {@link VendorInfoOption }
     *     
     */
    public VendorInfoOption getVendorInfoOption() {
        return vendorInfoOption;
    }

    /**
     * Sets the value of the vendorInfoOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorInfoOption }
     *     
     */
    public void setVendorInfoOption(VendorInfoOption value) {
        this.vendorInfoOption = value;
    }

    /**
     * Gets the value of the dnsServersOption property.
     * 
     * @return
     *     possible object is
     *     {@link DnsServersOption }
     *     
     */
    public DnsServersOption getDnsServersOption() {
        return dnsServersOption;
    }

    /**
     * Sets the value of the dnsServersOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DnsServersOption }
     *     
     */
    public void setDnsServersOption(DnsServersOption value) {
        this.dnsServersOption = value;
    }

    /**
     * Gets the value of the domainListOption property.
     * 
     * @return
     *     possible object is
     *     {@link DomainListOption }
     *     
     */
    public DomainListOption getDomainListOption() {
        return domainListOption;
    }

    /**
     * Sets the value of the domainListOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainListOption }
     *     
     */
    public void setDomainListOption(DomainListOption value) {
        this.domainListOption = value;
    }

    /**
     * Gets the value of the genericOptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Option }
     * 
     * 
     */
    public List<Option> getGenericOptions() {
        if (genericOptions == null) {
            genericOptions = new ArrayList<Option>();
        }
        return this.genericOptions;
    }

    /**
     * Gets the value of the filterGroups property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filterGroups property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilterGroups().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DhcpV6ServerConfig.FilterGroups }
     * 
     * 
     */
    public List<DhcpV6ServerConfig.FilterGroups> getFilterGroups() {
        if (filterGroups == null) {
            filterGroups = new ArrayList<DhcpV6ServerConfig.FilterGroups>();
        }
        return this.filterGroups;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DhcpV6ServerConfig.Links }
     * 
     * 
     */
    public List<DhcpV6ServerConfig.Links> getLinks() {
        if (links == null) {
            links = new ArrayList<DhcpV6ServerConfig.Links>();
        }
        return this.links;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{}name"/>
     *         &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
     *         &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
     *         &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
     *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
     *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
     *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
     *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
     *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
     *         &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
     *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "optionExpressions",
        "abcPolicy",
        "xyzPolicy",
        "genericPolicies",
        "preferenceOption",
        "serverUnicastOption",
        "statusCodeOption",
        "vendorInfoOption",
        "dnsServersOption",
        "domainListOption",
        "genericOptions"
    })
    public static class FilterGroups
        implements Serializable
    {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected List<OptionExpression> optionExpressions;
        protected Boolean abcPolicy;
        protected Integer xyzPolicy;
        protected List<Policy> genericPolicies;
        protected PreferenceOption preferenceOption;
        protected ServerUnicastOption serverUnicastOption;
        protected StatusCodeOption statusCodeOption;
        protected VendorInfoOption vendorInfoOption;
        protected DnsServersOption dnsServersOption;
        protected DomainListOption domainListOption;
        protected List<Option> genericOptions;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the optionExpressions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the optionExpressions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOptionExpressions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OptionExpression }
         * 
         * 
         */
        public List<OptionExpression> getOptionExpressions() {
            if (optionExpressions == null) {
                optionExpressions = new ArrayList<OptionExpression>();
            }
            return this.optionExpressions;
        }

        /**
         * Gets the value of the abcPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAbcPolicy() {
            return abcPolicy;
        }

        /**
         * Sets the value of the abcPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAbcPolicy(Boolean value) {
            this.abcPolicy = value;
        }

        /**
         * Gets the value of the xyzPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getXyzPolicy() {
            return xyzPolicy;
        }

        /**
         * Sets the value of the xyzPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setXyzPolicy(Integer value) {
            this.xyzPolicy = value;
        }

        /**
         * Gets the value of the genericPolicies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericPolicies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Policy }
         * 
         * 
         */
        public List<Policy> getGenericPolicies() {
            if (genericPolicies == null) {
                genericPolicies = new ArrayList<Policy>();
            }
            return this.genericPolicies;
        }

        /**
         * Gets the value of the preferenceOption property.
         * 
         * @return
         *     possible object is
         *     {@link PreferenceOption }
         *     
         */
        public PreferenceOption getPreferenceOption() {
            return preferenceOption;
        }

        /**
         * Sets the value of the preferenceOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link PreferenceOption }
         *     
         */
        public void setPreferenceOption(PreferenceOption value) {
            this.preferenceOption = value;
        }

        /**
         * Gets the value of the serverUnicastOption property.
         * 
         * @return
         *     possible object is
         *     {@link ServerUnicastOption }
         *     
         */
        public ServerUnicastOption getServerUnicastOption() {
            return serverUnicastOption;
        }

        /**
         * Sets the value of the serverUnicastOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServerUnicastOption }
         *     
         */
        public void setServerUnicastOption(ServerUnicastOption value) {
            this.serverUnicastOption = value;
        }

        /**
         * Gets the value of the statusCodeOption property.
         * 
         * @return
         *     possible object is
         *     {@link StatusCodeOption }
         *     
         */
        public StatusCodeOption getStatusCodeOption() {
            return statusCodeOption;
        }

        /**
         * Sets the value of the statusCodeOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusCodeOption }
         *     
         */
        public void setStatusCodeOption(StatusCodeOption value) {
            this.statusCodeOption = value;
        }

        /**
         * Gets the value of the vendorInfoOption property.
         * 
         * @return
         *     possible object is
         *     {@link VendorInfoOption }
         *     
         */
        public VendorInfoOption getVendorInfoOption() {
            return vendorInfoOption;
        }

        /**
         * Sets the value of the vendorInfoOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link VendorInfoOption }
         *     
         */
        public void setVendorInfoOption(VendorInfoOption value) {
            this.vendorInfoOption = value;
        }

        /**
         * Gets the value of the dnsServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link DnsServersOption }
         *     
         */
        public DnsServersOption getDnsServersOption() {
            return dnsServersOption;
        }

        /**
         * Sets the value of the dnsServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DnsServersOption }
         *     
         */
        public void setDnsServersOption(DnsServersOption value) {
            this.dnsServersOption = value;
        }

        /**
         * Gets the value of the domainListOption property.
         * 
         * @return
         *     possible object is
         *     {@link DomainListOption }
         *     
         */
        public DomainListOption getDomainListOption() {
            return domainListOption;
        }

        /**
         * Sets the value of the domainListOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainListOption }
         *     
         */
        public void setDomainListOption(DomainListOption value) {
            this.domainListOption = value;
        }

        /**
         * Gets the value of the genericOptions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericOptions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Option }
         * 
         * 
         */
        public List<Option> getGenericOptions() {
            if (genericOptions == null) {
                genericOptions = new ArrayList<Option>();
            }
            return this.genericOptions;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
     *         &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
     *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="serverIdOption" type="{}serverIdOption" minOccurs="0"/>
     *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
     *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
     *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
     *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
     *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
     *         &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
     *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="filterGroups" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{}name"/>
     *                   &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
     *                   &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
     *                   &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
     *                   &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
     *                   &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
     *                   &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
     *                   &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
     *                   &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
     *                   &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
     *                   &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "address",
        "abcPolicy",
        "xyzPolicy",
        "genericPolicies",
        "serverIdOption",
        "preferenceOption",
        "serverUnicastOption",
        "statusCodeOption",
        "vendorInfoOption",
        "dnsServersOption",
        "domainListOption",
        "genericOptions",
        "filterGroups"
    })
    public static class Links
        implements Serializable
    {

        @XmlElement(required = true)
        protected String address;
        protected Boolean abcPolicy;
        protected Integer xyzPolicy;
        protected List<Policy> genericPolicies;
        protected ServerIdOption serverIdOption;
        protected PreferenceOption preferenceOption;
        protected ServerUnicastOption serverUnicastOption;
        protected StatusCodeOption statusCodeOption;
        protected VendorInfoOption vendorInfoOption;
        protected DnsServersOption dnsServersOption;
        protected DomainListOption domainListOption;
        protected List<Option> genericOptions;
        protected List<DhcpV6ServerConfig.Links.FilterGroups> filterGroups;

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the abcPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isAbcPolicy() {
            return abcPolicy;
        }

        /**
         * Sets the value of the abcPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setAbcPolicy(Boolean value) {
            this.abcPolicy = value;
        }

        /**
         * Gets the value of the xyzPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getXyzPolicy() {
            return xyzPolicy;
        }

        /**
         * Sets the value of the xyzPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setXyzPolicy(Integer value) {
            this.xyzPolicy = value;
        }

        /**
         * Gets the value of the genericPolicies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericPolicies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Policy }
         * 
         * 
         */
        public List<Policy> getGenericPolicies() {
            if (genericPolicies == null) {
                genericPolicies = new ArrayList<Policy>();
            }
            return this.genericPolicies;
        }

        /**
         * Gets the value of the serverIdOption property.
         * 
         * @return
         *     possible object is
         *     {@link ServerIdOption }
         *     
         */
        public ServerIdOption getServerIdOption() {
            return serverIdOption;
        }

        /**
         * Sets the value of the serverIdOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServerIdOption }
         *     
         */
        public void setServerIdOption(ServerIdOption value) {
            this.serverIdOption = value;
        }

        /**
         * Gets the value of the preferenceOption property.
         * 
         * @return
         *     possible object is
         *     {@link PreferenceOption }
         *     
         */
        public PreferenceOption getPreferenceOption() {
            return preferenceOption;
        }

        /**
         * Sets the value of the preferenceOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link PreferenceOption }
         *     
         */
        public void setPreferenceOption(PreferenceOption value) {
            this.preferenceOption = value;
        }

        /**
         * Gets the value of the serverUnicastOption property.
         * 
         * @return
         *     possible object is
         *     {@link ServerUnicastOption }
         *     
         */
        public ServerUnicastOption getServerUnicastOption() {
            return serverUnicastOption;
        }

        /**
         * Sets the value of the serverUnicastOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServerUnicastOption }
         *     
         */
        public void setServerUnicastOption(ServerUnicastOption value) {
            this.serverUnicastOption = value;
        }

        /**
         * Gets the value of the statusCodeOption property.
         * 
         * @return
         *     possible object is
         *     {@link StatusCodeOption }
         *     
         */
        public StatusCodeOption getStatusCodeOption() {
            return statusCodeOption;
        }

        /**
         * Sets the value of the statusCodeOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusCodeOption }
         *     
         */
        public void setStatusCodeOption(StatusCodeOption value) {
            this.statusCodeOption = value;
        }

        /**
         * Gets the value of the vendorInfoOption property.
         * 
         * @return
         *     possible object is
         *     {@link VendorInfoOption }
         *     
         */
        public VendorInfoOption getVendorInfoOption() {
            return vendorInfoOption;
        }

        /**
         * Sets the value of the vendorInfoOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link VendorInfoOption }
         *     
         */
        public void setVendorInfoOption(VendorInfoOption value) {
            this.vendorInfoOption = value;
        }

        /**
         * Gets the value of the dnsServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link DnsServersOption }
         *     
         */
        public DnsServersOption getDnsServersOption() {
            return dnsServersOption;
        }

        /**
         * Sets the value of the dnsServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DnsServersOption }
         *     
         */
        public void setDnsServersOption(DnsServersOption value) {
            this.dnsServersOption = value;
        }

        /**
         * Gets the value of the domainListOption property.
         * 
         * @return
         *     possible object is
         *     {@link DomainListOption }
         *     
         */
        public DomainListOption getDomainListOption() {
            return domainListOption;
        }

        /**
         * Sets the value of the domainListOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainListOption }
         *     
         */
        public void setDomainListOption(DomainListOption value) {
            this.domainListOption = value;
        }

        /**
         * Gets the value of the genericOptions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericOptions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Option }
         * 
         * 
         */
        public List<Option> getGenericOptions() {
            if (genericOptions == null) {
                genericOptions = new ArrayList<Option>();
            }
            return this.genericOptions;
        }

        /**
         * Gets the value of the filterGroups property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filterGroups property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilterGroups().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DhcpV6ServerConfig.Links.FilterGroups }
         * 
         * 
         */
        public List<DhcpV6ServerConfig.Links.FilterGroups> getFilterGroups() {
            if (filterGroups == null) {
                filterGroups = new ArrayList<DhcpV6ServerConfig.Links.FilterGroups>();
            }
            return this.filterGroups;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{}name"/>
         *         &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
         *         &lt;element name="abcPolicy" type="{}abcPolicy" minOccurs="0"/>
         *         &lt;element name="xyzPolicy" type="{}xyzPolicy" minOccurs="0"/>
         *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
         *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
         *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
         *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
         *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
         *         &lt;element name="domainListOption" type="{}domainListOption" minOccurs="0"/>
         *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "optionExpressions",
            "abcPolicy",
            "xyzPolicy",
            "genericPolicies",
            "preferenceOption",
            "serverUnicastOption",
            "statusCodeOption",
            "vendorInfoOption",
            "dnsServersOption",
            "domainListOption",
            "genericOptions"
        })
        public static class FilterGroups
            implements Serializable
        {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected List<OptionExpression> optionExpressions;
            protected Boolean abcPolicy;
            protected Integer xyzPolicy;
            protected List<Policy> genericPolicies;
            protected PreferenceOption preferenceOption;
            protected ServerUnicastOption serverUnicastOption;
            protected StatusCodeOption statusCodeOption;
            protected VendorInfoOption vendorInfoOption;
            protected DnsServersOption dnsServersOption;
            protected DomainListOption domainListOption;
            protected List<Option> genericOptions;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the optionExpressions property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the optionExpressions property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOptionExpressions().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OptionExpression }
             * 
             * 
             */
            public List<OptionExpression> getOptionExpressions() {
                if (optionExpressions == null) {
                    optionExpressions = new ArrayList<OptionExpression>();
                }
                return this.optionExpressions;
            }

            /**
             * Gets the value of the abcPolicy property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isAbcPolicy() {
                return abcPolicy;
            }

            /**
             * Sets the value of the abcPolicy property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setAbcPolicy(Boolean value) {
                this.abcPolicy = value;
            }

            /**
             * Gets the value of the xyzPolicy property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getXyzPolicy() {
                return xyzPolicy;
            }

            /**
             * Sets the value of the xyzPolicy property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setXyzPolicy(Integer value) {
                this.xyzPolicy = value;
            }

            /**
             * Gets the value of the genericPolicies property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGenericPolicies().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Policy }
             * 
             * 
             */
            public List<Policy> getGenericPolicies() {
                if (genericPolicies == null) {
                    genericPolicies = new ArrayList<Policy>();
                }
                return this.genericPolicies;
            }

            /**
             * Gets the value of the preferenceOption property.
             * 
             * @return
             *     possible object is
             *     {@link PreferenceOption }
             *     
             */
            public PreferenceOption getPreferenceOption() {
                return preferenceOption;
            }

            /**
             * Sets the value of the preferenceOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link PreferenceOption }
             *     
             */
            public void setPreferenceOption(PreferenceOption value) {
                this.preferenceOption = value;
            }

            /**
             * Gets the value of the serverUnicastOption property.
             * 
             * @return
             *     possible object is
             *     {@link ServerUnicastOption }
             *     
             */
            public ServerUnicastOption getServerUnicastOption() {
                return serverUnicastOption;
            }

            /**
             * Sets the value of the serverUnicastOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServerUnicastOption }
             *     
             */
            public void setServerUnicastOption(ServerUnicastOption value) {
                this.serverUnicastOption = value;
            }

            /**
             * Gets the value of the statusCodeOption property.
             * 
             * @return
             *     possible object is
             *     {@link StatusCodeOption }
             *     
             */
            public StatusCodeOption getStatusCodeOption() {
                return statusCodeOption;
            }

            /**
             * Sets the value of the statusCodeOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link StatusCodeOption }
             *     
             */
            public void setStatusCodeOption(StatusCodeOption value) {
                this.statusCodeOption = value;
            }

            /**
             * Gets the value of the vendorInfoOption property.
             * 
             * @return
             *     possible object is
             *     {@link VendorInfoOption }
             *     
             */
            public VendorInfoOption getVendorInfoOption() {
                return vendorInfoOption;
            }

            /**
             * Sets the value of the vendorInfoOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link VendorInfoOption }
             *     
             */
            public void setVendorInfoOption(VendorInfoOption value) {
                this.vendorInfoOption = value;
            }

            /**
             * Gets the value of the dnsServersOption property.
             * 
             * @return
             *     possible object is
             *     {@link DnsServersOption }
             *     
             */
            public DnsServersOption getDnsServersOption() {
                return dnsServersOption;
            }

            /**
             * Sets the value of the dnsServersOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link DnsServersOption }
             *     
             */
            public void setDnsServersOption(DnsServersOption value) {
                this.dnsServersOption = value;
            }

            /**
             * Gets the value of the domainListOption property.
             * 
             * @return
             *     possible object is
             *     {@link DomainListOption }
             *     
             */
            public DomainListOption getDomainListOption() {
                return domainListOption;
            }

            /**
             * Sets the value of the domainListOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainListOption }
             *     
             */
            public void setDomainListOption(DomainListOption value) {
                this.domainListOption = value;
            }

            /**
             * Gets the value of the genericOptions property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGenericOptions().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Option }
             * 
             * 
             */
            public List<Option> getGenericOptions() {
                if (genericOptions == null) {
                    genericOptions = new ArrayList<Option>();
                }
                return this.genericOptions;
            }

        }

    }

}
