//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.06 at 11:28:50 PM EDT 
//


package com.agr.dhcpv6.server.config.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
 *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="serverIdOption" type="{}serverIdOption"/>
 *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *         &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
 *         &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
 *         &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
 *         &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
 *         &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
 *         &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
 *         &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
 *         &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
 *         &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
 *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="filters" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{}name"/>
 *                   &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
 *                   &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
 *                   &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *                   &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *                   &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *                   &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *                   &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *                   &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
 *                   &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
 *                   &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
 *                   &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
 *                   &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
 *                   &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
 *                   &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
 *                   &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
 *                   &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
 *                   &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="links" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{}name"/>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
 *                   &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="serverIdOption" type="{}serverIdOption" minOccurs="0"/>
 *                   &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *                   &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *                   &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *                   &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *                   &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *                   &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
 *                   &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
 *                   &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
 *                   &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
 *                   &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
 *                   &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
 *                   &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
 *                   &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
 *                   &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
 *                   &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="filters" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{}name"/>
 *                             &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
 *                             &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
 *                             &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
 *                             &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
 *                             &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
 *                             &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
 *                             &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
 *                             &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
 *                             &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
 *                             &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
 *                             &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
 *                             &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
 *                             &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
 *                             &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
 *                             &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
 *                             &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
 *                             &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sendRequestedOptionsOnlyPolicy",
    "genericPolicies",
    "serverIdOption",
    "preferenceOption",
    "serverUnicastOption",
    "statusCodeOption",
    "vendorInfoOption",
    "dnsServersOption",
    "domainSearchListOption",
    "sipServerAddressesOption",
    "sipServerDomainNamesOption",
    "nisServersOption",
    "nisDomainNameOption",
    "nisPlusServersOption",
    "nisPlusDomainNameOption",
    "sntpServersOption",
    "infoRefreshTimeOption",
    "genericOptions",
    "filters",
    "links"
})
@XmlRootElement(name = "dhcpV6ServerConfig")
public class DhcpV6ServerConfig
    implements Serializable
{

    protected Boolean sendRequestedOptionsOnlyPolicy;
    protected List<Policy> genericPolicies;
    @XmlElement(required = true)
    protected ServerIdOption serverIdOption;
    protected PreferenceOption preferenceOption;
    protected ServerUnicastOption serverUnicastOption;
    protected StatusCodeOption statusCodeOption;
    protected VendorInfoOption vendorInfoOption;
    protected DnsServersOption dnsServersOption;
    protected DomainSearchListOption domainSearchListOption;
    protected SipServerAddressesOption sipServerAddressesOption;
    protected SipServerDomainNamesOption sipServerDomainNamesOption;
    protected NisServersOption nisServersOption;
    protected NisDomainNameOption nisDomainNameOption;
    protected NisPlusServersOption nisPlusServersOption;
    protected NisPlusDomainNameOption nisPlusDomainNameOption;
    protected SntpServersOption sntpServersOption;
    protected InfoRefreshTimeOption infoRefreshTimeOption;
    protected List<Option> genericOptions;
    protected List<DhcpV6ServerConfig.Filters> filters;
    protected List<DhcpV6ServerConfig.Links> links;

    /**
     * Gets the value of the sendRequestedOptionsOnlyPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSendRequestedOptionsOnlyPolicy() {
        return sendRequestedOptionsOnlyPolicy;
    }

    /**
     * Sets the value of the sendRequestedOptionsOnlyPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSendRequestedOptionsOnlyPolicy(Boolean value) {
        this.sendRequestedOptionsOnlyPolicy = value;
    }

    /**
     * Gets the value of the genericPolicies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericPolicies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Policy }
     * 
     * 
     */
    public List<Policy> getGenericPolicies() {
        if (genericPolicies == null) {
            genericPolicies = new ArrayList<Policy>();
        }
        return this.genericPolicies;
    }

    /**
     * Gets the value of the serverIdOption property.
     * 
     * @return
     *     possible object is
     *     {@link ServerIdOption }
     *     
     */
    public ServerIdOption getServerIdOption() {
        return serverIdOption;
    }

    /**
     * Sets the value of the serverIdOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerIdOption }
     *     
     */
    public void setServerIdOption(ServerIdOption value) {
        this.serverIdOption = value;
    }

    /**
     * Gets the value of the preferenceOption property.
     * 
     * @return
     *     possible object is
     *     {@link PreferenceOption }
     *     
     */
    public PreferenceOption getPreferenceOption() {
        return preferenceOption;
    }

    /**
     * Sets the value of the preferenceOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreferenceOption }
     *     
     */
    public void setPreferenceOption(PreferenceOption value) {
        this.preferenceOption = value;
    }

    /**
     * Gets the value of the serverUnicastOption property.
     * 
     * @return
     *     possible object is
     *     {@link ServerUnicastOption }
     *     
     */
    public ServerUnicastOption getServerUnicastOption() {
        return serverUnicastOption;
    }

    /**
     * Sets the value of the serverUnicastOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerUnicastOption }
     *     
     */
    public void setServerUnicastOption(ServerUnicastOption value) {
        this.serverUnicastOption = value;
    }

    /**
     * Gets the value of the statusCodeOption property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodeOption }
     *     
     */
    public StatusCodeOption getStatusCodeOption() {
        return statusCodeOption;
    }

    /**
     * Sets the value of the statusCodeOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodeOption }
     *     
     */
    public void setStatusCodeOption(StatusCodeOption value) {
        this.statusCodeOption = value;
    }

    /**
     * Gets the value of the vendorInfoOption property.
     * 
     * @return
     *     possible object is
     *     {@link VendorInfoOption }
     *     
     */
    public VendorInfoOption getVendorInfoOption() {
        return vendorInfoOption;
    }

    /**
     * Sets the value of the vendorInfoOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorInfoOption }
     *     
     */
    public void setVendorInfoOption(VendorInfoOption value) {
        this.vendorInfoOption = value;
    }

    /**
     * Gets the value of the dnsServersOption property.
     * 
     * @return
     *     possible object is
     *     {@link DnsServersOption }
     *     
     */
    public DnsServersOption getDnsServersOption() {
        return dnsServersOption;
    }

    /**
     * Sets the value of the dnsServersOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DnsServersOption }
     *     
     */
    public void setDnsServersOption(DnsServersOption value) {
        this.dnsServersOption = value;
    }

    /**
     * Gets the value of the domainSearchListOption property.
     * 
     * @return
     *     possible object is
     *     {@link DomainSearchListOption }
     *     
     */
    public DomainSearchListOption getDomainSearchListOption() {
        return domainSearchListOption;
    }

    /**
     * Sets the value of the domainSearchListOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link DomainSearchListOption }
     *     
     */
    public void setDomainSearchListOption(DomainSearchListOption value) {
        this.domainSearchListOption = value;
    }

    /**
     * Gets the value of the sipServerAddressesOption property.
     * 
     * @return
     *     possible object is
     *     {@link SipServerAddressesOption }
     *     
     */
    public SipServerAddressesOption getSipServerAddressesOption() {
        return sipServerAddressesOption;
    }

    /**
     * Sets the value of the sipServerAddressesOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link SipServerAddressesOption }
     *     
     */
    public void setSipServerAddressesOption(SipServerAddressesOption value) {
        this.sipServerAddressesOption = value;
    }

    /**
     * Gets the value of the sipServerDomainNamesOption property.
     * 
     * @return
     *     possible object is
     *     {@link SipServerDomainNamesOption }
     *     
     */
    public SipServerDomainNamesOption getSipServerDomainNamesOption() {
        return sipServerDomainNamesOption;
    }

    /**
     * Sets the value of the sipServerDomainNamesOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link SipServerDomainNamesOption }
     *     
     */
    public void setSipServerDomainNamesOption(SipServerDomainNamesOption value) {
        this.sipServerDomainNamesOption = value;
    }

    /**
     * Gets the value of the nisServersOption property.
     * 
     * @return
     *     possible object is
     *     {@link NisServersOption }
     *     
     */
    public NisServersOption getNisServersOption() {
        return nisServersOption;
    }

    /**
     * Sets the value of the nisServersOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NisServersOption }
     *     
     */
    public void setNisServersOption(NisServersOption value) {
        this.nisServersOption = value;
    }

    /**
     * Gets the value of the nisDomainNameOption property.
     * 
     * @return
     *     possible object is
     *     {@link NisDomainNameOption }
     *     
     */
    public NisDomainNameOption getNisDomainNameOption() {
        return nisDomainNameOption;
    }

    /**
     * Sets the value of the nisDomainNameOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NisDomainNameOption }
     *     
     */
    public void setNisDomainNameOption(NisDomainNameOption value) {
        this.nisDomainNameOption = value;
    }

    /**
     * Gets the value of the nisPlusServersOption property.
     * 
     * @return
     *     possible object is
     *     {@link NisPlusServersOption }
     *     
     */
    public NisPlusServersOption getNisPlusServersOption() {
        return nisPlusServersOption;
    }

    /**
     * Sets the value of the nisPlusServersOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NisPlusServersOption }
     *     
     */
    public void setNisPlusServersOption(NisPlusServersOption value) {
        this.nisPlusServersOption = value;
    }

    /**
     * Gets the value of the nisPlusDomainNameOption property.
     * 
     * @return
     *     possible object is
     *     {@link NisPlusDomainNameOption }
     *     
     */
    public NisPlusDomainNameOption getNisPlusDomainNameOption() {
        return nisPlusDomainNameOption;
    }

    /**
     * Sets the value of the nisPlusDomainNameOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link NisPlusDomainNameOption }
     *     
     */
    public void setNisPlusDomainNameOption(NisPlusDomainNameOption value) {
        this.nisPlusDomainNameOption = value;
    }

    /**
     * Gets the value of the sntpServersOption property.
     * 
     * @return
     *     possible object is
     *     {@link SntpServersOption }
     *     
     */
    public SntpServersOption getSntpServersOption() {
        return sntpServersOption;
    }

    /**
     * Sets the value of the sntpServersOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link SntpServersOption }
     *     
     */
    public void setSntpServersOption(SntpServersOption value) {
        this.sntpServersOption = value;
    }

    /**
     * Gets the value of the infoRefreshTimeOption property.
     * 
     * @return
     *     possible object is
     *     {@link InfoRefreshTimeOption }
     *     
     */
    public InfoRefreshTimeOption getInfoRefreshTimeOption() {
        return infoRefreshTimeOption;
    }

    /**
     * Sets the value of the infoRefreshTimeOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoRefreshTimeOption }
     *     
     */
    public void setInfoRefreshTimeOption(InfoRefreshTimeOption value) {
        this.infoRefreshTimeOption = value;
    }

    /**
     * Gets the value of the genericOptions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGenericOptions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Option }
     * 
     * 
     */
    public List<Option> getGenericOptions() {
        if (genericOptions == null) {
            genericOptions = new ArrayList<Option>();
        }
        return this.genericOptions;
    }

    /**
     * Gets the value of the filters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the filters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFilters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DhcpV6ServerConfig.Filters }
     * 
     * 
     */
    public List<DhcpV6ServerConfig.Filters> getFilters() {
        if (filters == null) {
            filters = new ArrayList<DhcpV6ServerConfig.Filters>();
        }
        return this.filters;
    }

    /**
     * Gets the value of the links property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the links property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DhcpV6ServerConfig.Links }
     * 
     * 
     */
    public List<DhcpV6ServerConfig.Links> getLinks() {
        if (links == null) {
            links = new ArrayList<DhcpV6ServerConfig.Links>();
        }
        return this.links;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{}name"/>
     *         &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
     *         &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
     *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
     *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
     *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
     *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
     *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
     *         &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
     *         &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
     *         &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
     *         &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
     *         &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
     *         &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
     *         &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
     *         &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
     *         &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
     *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "optionExpressions",
        "sendRequestedOptionsOnlyPolicy",
        "genericPolicies",
        "preferenceOption",
        "serverUnicastOption",
        "statusCodeOption",
        "vendorInfoOption",
        "dnsServersOption",
        "domainSearchListOption",
        "sipServerAddressesOption",
        "sipServerDomainNamesOption",
        "nisServersOption",
        "nisDomainNameOption",
        "nisPlusServersOption",
        "nisPlusDomainNameOption",
        "sntpServersOption",
        "infoRefreshTimeOption",
        "genericOptions"
    })
    public static class Filters
        implements Serializable
    {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected List<OptionExpression> optionExpressions;
        protected Boolean sendRequestedOptionsOnlyPolicy;
        protected List<Policy> genericPolicies;
        protected PreferenceOption preferenceOption;
        protected ServerUnicastOption serverUnicastOption;
        protected StatusCodeOption statusCodeOption;
        protected VendorInfoOption vendorInfoOption;
        protected DnsServersOption dnsServersOption;
        protected DomainSearchListOption domainSearchListOption;
        protected SipServerAddressesOption sipServerAddressesOption;
        protected SipServerDomainNamesOption sipServerDomainNamesOption;
        protected NisServersOption nisServersOption;
        protected NisDomainNameOption nisDomainNameOption;
        protected NisPlusServersOption nisPlusServersOption;
        protected NisPlusDomainNameOption nisPlusDomainNameOption;
        protected SntpServersOption sntpServersOption;
        protected InfoRefreshTimeOption infoRefreshTimeOption;
        protected List<Option> genericOptions;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the optionExpressions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the optionExpressions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getOptionExpressions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link OptionExpression }
         * 
         * 
         */
        public List<OptionExpression> getOptionExpressions() {
            if (optionExpressions == null) {
                optionExpressions = new ArrayList<OptionExpression>();
            }
            return this.optionExpressions;
        }

        /**
         * Gets the value of the sendRequestedOptionsOnlyPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSendRequestedOptionsOnlyPolicy() {
            return sendRequestedOptionsOnlyPolicy;
        }

        /**
         * Sets the value of the sendRequestedOptionsOnlyPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSendRequestedOptionsOnlyPolicy(Boolean value) {
            this.sendRequestedOptionsOnlyPolicy = value;
        }

        /**
         * Gets the value of the genericPolicies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericPolicies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Policy }
         * 
         * 
         */
        public List<Policy> getGenericPolicies() {
            if (genericPolicies == null) {
                genericPolicies = new ArrayList<Policy>();
            }
            return this.genericPolicies;
        }

        /**
         * Gets the value of the preferenceOption property.
         * 
         * @return
         *     possible object is
         *     {@link PreferenceOption }
         *     
         */
        public PreferenceOption getPreferenceOption() {
            return preferenceOption;
        }

        /**
         * Sets the value of the preferenceOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link PreferenceOption }
         *     
         */
        public void setPreferenceOption(PreferenceOption value) {
            this.preferenceOption = value;
        }

        /**
         * Gets the value of the serverUnicastOption property.
         * 
         * @return
         *     possible object is
         *     {@link ServerUnicastOption }
         *     
         */
        public ServerUnicastOption getServerUnicastOption() {
            return serverUnicastOption;
        }

        /**
         * Sets the value of the serverUnicastOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServerUnicastOption }
         *     
         */
        public void setServerUnicastOption(ServerUnicastOption value) {
            this.serverUnicastOption = value;
        }

        /**
         * Gets the value of the statusCodeOption property.
         * 
         * @return
         *     possible object is
         *     {@link StatusCodeOption }
         *     
         */
        public StatusCodeOption getStatusCodeOption() {
            return statusCodeOption;
        }

        /**
         * Sets the value of the statusCodeOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusCodeOption }
         *     
         */
        public void setStatusCodeOption(StatusCodeOption value) {
            this.statusCodeOption = value;
        }

        /**
         * Gets the value of the vendorInfoOption property.
         * 
         * @return
         *     possible object is
         *     {@link VendorInfoOption }
         *     
         */
        public VendorInfoOption getVendorInfoOption() {
            return vendorInfoOption;
        }

        /**
         * Sets the value of the vendorInfoOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link VendorInfoOption }
         *     
         */
        public void setVendorInfoOption(VendorInfoOption value) {
            this.vendorInfoOption = value;
        }

        /**
         * Gets the value of the dnsServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link DnsServersOption }
         *     
         */
        public DnsServersOption getDnsServersOption() {
            return dnsServersOption;
        }

        /**
         * Sets the value of the dnsServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DnsServersOption }
         *     
         */
        public void setDnsServersOption(DnsServersOption value) {
            this.dnsServersOption = value;
        }

        /**
         * Gets the value of the domainSearchListOption property.
         * 
         * @return
         *     possible object is
         *     {@link DomainSearchListOption }
         *     
         */
        public DomainSearchListOption getDomainSearchListOption() {
            return domainSearchListOption;
        }

        /**
         * Sets the value of the domainSearchListOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainSearchListOption }
         *     
         */
        public void setDomainSearchListOption(DomainSearchListOption value) {
            this.domainSearchListOption = value;
        }

        /**
         * Gets the value of the sipServerAddressesOption property.
         * 
         * @return
         *     possible object is
         *     {@link SipServerAddressesOption }
         *     
         */
        public SipServerAddressesOption getSipServerAddressesOption() {
            return sipServerAddressesOption;
        }

        /**
         * Sets the value of the sipServerAddressesOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link SipServerAddressesOption }
         *     
         */
        public void setSipServerAddressesOption(SipServerAddressesOption value) {
            this.sipServerAddressesOption = value;
        }

        /**
         * Gets the value of the sipServerDomainNamesOption property.
         * 
         * @return
         *     possible object is
         *     {@link SipServerDomainNamesOption }
         *     
         */
        public SipServerDomainNamesOption getSipServerDomainNamesOption() {
            return sipServerDomainNamesOption;
        }

        /**
         * Sets the value of the sipServerDomainNamesOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link SipServerDomainNamesOption }
         *     
         */
        public void setSipServerDomainNamesOption(SipServerDomainNamesOption value) {
            this.sipServerDomainNamesOption = value;
        }

        /**
         * Gets the value of the nisServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisServersOption }
         *     
         */
        public NisServersOption getNisServersOption() {
            return nisServersOption;
        }

        /**
         * Sets the value of the nisServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisServersOption }
         *     
         */
        public void setNisServersOption(NisServersOption value) {
            this.nisServersOption = value;
        }

        /**
         * Gets the value of the nisDomainNameOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisDomainNameOption }
         *     
         */
        public NisDomainNameOption getNisDomainNameOption() {
            return nisDomainNameOption;
        }

        /**
         * Sets the value of the nisDomainNameOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisDomainNameOption }
         *     
         */
        public void setNisDomainNameOption(NisDomainNameOption value) {
            this.nisDomainNameOption = value;
        }

        /**
         * Gets the value of the nisPlusServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisPlusServersOption }
         *     
         */
        public NisPlusServersOption getNisPlusServersOption() {
            return nisPlusServersOption;
        }

        /**
         * Sets the value of the nisPlusServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisPlusServersOption }
         *     
         */
        public void setNisPlusServersOption(NisPlusServersOption value) {
            this.nisPlusServersOption = value;
        }

        /**
         * Gets the value of the nisPlusDomainNameOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisPlusDomainNameOption }
         *     
         */
        public NisPlusDomainNameOption getNisPlusDomainNameOption() {
            return nisPlusDomainNameOption;
        }

        /**
         * Sets the value of the nisPlusDomainNameOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisPlusDomainNameOption }
         *     
         */
        public void setNisPlusDomainNameOption(NisPlusDomainNameOption value) {
            this.nisPlusDomainNameOption = value;
        }

        /**
         * Gets the value of the sntpServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link SntpServersOption }
         *     
         */
        public SntpServersOption getSntpServersOption() {
            return sntpServersOption;
        }

        /**
         * Sets the value of the sntpServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link SntpServersOption }
         *     
         */
        public void setSntpServersOption(SntpServersOption value) {
            this.sntpServersOption = value;
        }

        /**
         * Gets the value of the infoRefreshTimeOption property.
         * 
         * @return
         *     possible object is
         *     {@link InfoRefreshTimeOption }
         *     
         */
        public InfoRefreshTimeOption getInfoRefreshTimeOption() {
            return infoRefreshTimeOption;
        }

        /**
         * Sets the value of the infoRefreshTimeOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link InfoRefreshTimeOption }
         *     
         */
        public void setInfoRefreshTimeOption(InfoRefreshTimeOption value) {
            this.infoRefreshTimeOption = value;
        }

        /**
         * Gets the value of the genericOptions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericOptions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Option }
         * 
         * 
         */
        public List<Option> getGenericOptions() {
            if (genericOptions == null) {
                genericOptions = new ArrayList<Option>();
            }
            return this.genericOptions;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{}name"/>
     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
     *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="serverIdOption" type="{}serverIdOption" minOccurs="0"/>
     *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
     *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
     *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
     *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
     *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
     *         &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
     *         &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
     *         &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
     *         &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
     *         &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
     *         &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
     *         &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
     *         &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
     *         &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
     *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="filters" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{}name"/>
     *                   &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
     *                   &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
     *                   &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
     *                   &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
     *                   &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
     *                   &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
     *                   &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
     *                   &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
     *                   &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
     *                   &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
     *                   &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
     *                   &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
     *                   &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
     *                   &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
     *                   &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
     *                   &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
     *                   &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "address",
        "sendRequestedOptionsOnlyPolicy",
        "genericPolicies",
        "serverIdOption",
        "preferenceOption",
        "serverUnicastOption",
        "statusCodeOption",
        "vendorInfoOption",
        "dnsServersOption",
        "domainSearchListOption",
        "sipServerAddressesOption",
        "sipServerDomainNamesOption",
        "nisServersOption",
        "nisDomainNameOption",
        "nisPlusServersOption",
        "nisPlusDomainNameOption",
        "sntpServersOption",
        "infoRefreshTimeOption",
        "genericOptions",
        "filters"
    })
    public static class Links
        implements Serializable
    {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String address;
        protected Boolean sendRequestedOptionsOnlyPolicy;
        protected List<Policy> genericPolicies;
        protected ServerIdOption serverIdOption;
        protected PreferenceOption preferenceOption;
        protected ServerUnicastOption serverUnicastOption;
        protected StatusCodeOption statusCodeOption;
        protected VendorInfoOption vendorInfoOption;
        protected DnsServersOption dnsServersOption;
        protected DomainSearchListOption domainSearchListOption;
        protected SipServerAddressesOption sipServerAddressesOption;
        protected SipServerDomainNamesOption sipServerDomainNamesOption;
        protected NisServersOption nisServersOption;
        protected NisDomainNameOption nisDomainNameOption;
        protected NisPlusServersOption nisPlusServersOption;
        protected NisPlusDomainNameOption nisPlusDomainNameOption;
        protected SntpServersOption sntpServersOption;
        protected InfoRefreshTimeOption infoRefreshTimeOption;
        protected List<Option> genericOptions;
        protected List<DhcpV6ServerConfig.Links.Filters> filters;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the sendRequestedOptionsOnlyPolicy property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public Boolean isSendRequestedOptionsOnlyPolicy() {
            return sendRequestedOptionsOnlyPolicy;
        }

        /**
         * Sets the value of the sendRequestedOptionsOnlyPolicy property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setSendRequestedOptionsOnlyPolicy(Boolean value) {
            this.sendRequestedOptionsOnlyPolicy = value;
        }

        /**
         * Gets the value of the genericPolicies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericPolicies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Policy }
         * 
         * 
         */
        public List<Policy> getGenericPolicies() {
            if (genericPolicies == null) {
                genericPolicies = new ArrayList<Policy>();
            }
            return this.genericPolicies;
        }

        /**
         * Gets the value of the serverIdOption property.
         * 
         * @return
         *     possible object is
         *     {@link ServerIdOption }
         *     
         */
        public ServerIdOption getServerIdOption() {
            return serverIdOption;
        }

        /**
         * Sets the value of the serverIdOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServerIdOption }
         *     
         */
        public void setServerIdOption(ServerIdOption value) {
            this.serverIdOption = value;
        }

        /**
         * Gets the value of the preferenceOption property.
         * 
         * @return
         *     possible object is
         *     {@link PreferenceOption }
         *     
         */
        public PreferenceOption getPreferenceOption() {
            return preferenceOption;
        }

        /**
         * Sets the value of the preferenceOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link PreferenceOption }
         *     
         */
        public void setPreferenceOption(PreferenceOption value) {
            this.preferenceOption = value;
        }

        /**
         * Gets the value of the serverUnicastOption property.
         * 
         * @return
         *     possible object is
         *     {@link ServerUnicastOption }
         *     
         */
        public ServerUnicastOption getServerUnicastOption() {
            return serverUnicastOption;
        }

        /**
         * Sets the value of the serverUnicastOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServerUnicastOption }
         *     
         */
        public void setServerUnicastOption(ServerUnicastOption value) {
            this.serverUnicastOption = value;
        }

        /**
         * Gets the value of the statusCodeOption property.
         * 
         * @return
         *     possible object is
         *     {@link StatusCodeOption }
         *     
         */
        public StatusCodeOption getStatusCodeOption() {
            return statusCodeOption;
        }

        /**
         * Sets the value of the statusCodeOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link StatusCodeOption }
         *     
         */
        public void setStatusCodeOption(StatusCodeOption value) {
            this.statusCodeOption = value;
        }

        /**
         * Gets the value of the vendorInfoOption property.
         * 
         * @return
         *     possible object is
         *     {@link VendorInfoOption }
         *     
         */
        public VendorInfoOption getVendorInfoOption() {
            return vendorInfoOption;
        }

        /**
         * Sets the value of the vendorInfoOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link VendorInfoOption }
         *     
         */
        public void setVendorInfoOption(VendorInfoOption value) {
            this.vendorInfoOption = value;
        }

        /**
         * Gets the value of the dnsServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link DnsServersOption }
         *     
         */
        public DnsServersOption getDnsServersOption() {
            return dnsServersOption;
        }

        /**
         * Sets the value of the dnsServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DnsServersOption }
         *     
         */
        public void setDnsServersOption(DnsServersOption value) {
            this.dnsServersOption = value;
        }

        /**
         * Gets the value of the domainSearchListOption property.
         * 
         * @return
         *     possible object is
         *     {@link DomainSearchListOption }
         *     
         */
        public DomainSearchListOption getDomainSearchListOption() {
            return domainSearchListOption;
        }

        /**
         * Sets the value of the domainSearchListOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link DomainSearchListOption }
         *     
         */
        public void setDomainSearchListOption(DomainSearchListOption value) {
            this.domainSearchListOption = value;
        }

        /**
         * Gets the value of the sipServerAddressesOption property.
         * 
         * @return
         *     possible object is
         *     {@link SipServerAddressesOption }
         *     
         */
        public SipServerAddressesOption getSipServerAddressesOption() {
            return sipServerAddressesOption;
        }

        /**
         * Sets the value of the sipServerAddressesOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link SipServerAddressesOption }
         *     
         */
        public void setSipServerAddressesOption(SipServerAddressesOption value) {
            this.sipServerAddressesOption = value;
        }

        /**
         * Gets the value of the sipServerDomainNamesOption property.
         * 
         * @return
         *     possible object is
         *     {@link SipServerDomainNamesOption }
         *     
         */
        public SipServerDomainNamesOption getSipServerDomainNamesOption() {
            return sipServerDomainNamesOption;
        }

        /**
         * Sets the value of the sipServerDomainNamesOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link SipServerDomainNamesOption }
         *     
         */
        public void setSipServerDomainNamesOption(SipServerDomainNamesOption value) {
            this.sipServerDomainNamesOption = value;
        }

        /**
         * Gets the value of the nisServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisServersOption }
         *     
         */
        public NisServersOption getNisServersOption() {
            return nisServersOption;
        }

        /**
         * Sets the value of the nisServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisServersOption }
         *     
         */
        public void setNisServersOption(NisServersOption value) {
            this.nisServersOption = value;
        }

        /**
         * Gets the value of the nisDomainNameOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisDomainNameOption }
         *     
         */
        public NisDomainNameOption getNisDomainNameOption() {
            return nisDomainNameOption;
        }

        /**
         * Sets the value of the nisDomainNameOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisDomainNameOption }
         *     
         */
        public void setNisDomainNameOption(NisDomainNameOption value) {
            this.nisDomainNameOption = value;
        }

        /**
         * Gets the value of the nisPlusServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisPlusServersOption }
         *     
         */
        public NisPlusServersOption getNisPlusServersOption() {
            return nisPlusServersOption;
        }

        /**
         * Sets the value of the nisPlusServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisPlusServersOption }
         *     
         */
        public void setNisPlusServersOption(NisPlusServersOption value) {
            this.nisPlusServersOption = value;
        }

        /**
         * Gets the value of the nisPlusDomainNameOption property.
         * 
         * @return
         *     possible object is
         *     {@link NisPlusDomainNameOption }
         *     
         */
        public NisPlusDomainNameOption getNisPlusDomainNameOption() {
            return nisPlusDomainNameOption;
        }

        /**
         * Sets the value of the nisPlusDomainNameOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link NisPlusDomainNameOption }
         *     
         */
        public void setNisPlusDomainNameOption(NisPlusDomainNameOption value) {
            this.nisPlusDomainNameOption = value;
        }

        /**
         * Gets the value of the sntpServersOption property.
         * 
         * @return
         *     possible object is
         *     {@link SntpServersOption }
         *     
         */
        public SntpServersOption getSntpServersOption() {
            return sntpServersOption;
        }

        /**
         * Sets the value of the sntpServersOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link SntpServersOption }
         *     
         */
        public void setSntpServersOption(SntpServersOption value) {
            this.sntpServersOption = value;
        }

        /**
         * Gets the value of the infoRefreshTimeOption property.
         * 
         * @return
         *     possible object is
         *     {@link InfoRefreshTimeOption }
         *     
         */
        public InfoRefreshTimeOption getInfoRefreshTimeOption() {
            return infoRefreshTimeOption;
        }

        /**
         * Sets the value of the infoRefreshTimeOption property.
         * 
         * @param value
         *     allowed object is
         *     {@link InfoRefreshTimeOption }
         *     
         */
        public void setInfoRefreshTimeOption(InfoRefreshTimeOption value) {
            this.infoRefreshTimeOption = value;
        }

        /**
         * Gets the value of the genericOptions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenericOptions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Option }
         * 
         * 
         */
        public List<Option> getGenericOptions() {
            if (genericOptions == null) {
                genericOptions = new ArrayList<Option>();
            }
            return this.genericOptions;
        }

        /**
         * Gets the value of the filters property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the filters property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFilters().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DhcpV6ServerConfig.Links.Filters }
         * 
         * 
         */
        public List<DhcpV6ServerConfig.Links.Filters> getFilters() {
            if (filters == null) {
                filters = new ArrayList<DhcpV6ServerConfig.Links.Filters>();
            }
            return this.filters;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{}name"/>
         *         &lt;element name="optionExpressions" type="{}optionExpression" maxOccurs="unbounded"/>
         *         &lt;element name="sendRequestedOptionsOnlyPolicy" type="{}sendRequestedOptionsOnlyPolicy" minOccurs="0"/>
         *         &lt;element name="genericPolicies" type="{}policy" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element name="preferenceOption" type="{}preferenceOption" minOccurs="0"/>
         *         &lt;element name="serverUnicastOption" type="{}serverUnicastOption" minOccurs="0"/>
         *         &lt;element name="statusCodeOption" type="{}statusCodeOption" minOccurs="0"/>
         *         &lt;element name="vendorInfoOption" type="{}vendorInfoOption" minOccurs="0"/>
         *         &lt;element name="dnsServersOption" type="{}dnsServersOption" minOccurs="0"/>
         *         &lt;element name="domainSearchListOption" type="{}domainSearchListOption" minOccurs="0"/>
         *         &lt;element name="sipServerAddressesOption" type="{}sipServerAddressesOption" minOccurs="0"/>
         *         &lt;element name="sipServerDomainNamesOption" type="{}sipServerDomainNamesOption" minOccurs="0"/>
         *         &lt;element name="nisServersOption" type="{}nisServersOption" minOccurs="0"/>
         *         &lt;element name="nisDomainNameOption" type="{}nisDomainNameOption" minOccurs="0"/>
         *         &lt;element name="nisPlusServersOption" type="{}nisPlusServersOption" minOccurs="0"/>
         *         &lt;element name="nisPlusDomainNameOption" type="{}nisPlusDomainNameOption" minOccurs="0"/>
         *         &lt;element name="sntpServersOption" type="{}sntpServersOption" minOccurs="0"/>
         *         &lt;element name="infoRefreshTimeOption" type="{}infoRefreshTimeOption" minOccurs="0"/>
         *         &lt;element name="genericOptions" type="{}option" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "optionExpressions",
            "sendRequestedOptionsOnlyPolicy",
            "genericPolicies",
            "preferenceOption",
            "serverUnicastOption",
            "statusCodeOption",
            "vendorInfoOption",
            "dnsServersOption",
            "domainSearchListOption",
            "sipServerAddressesOption",
            "sipServerDomainNamesOption",
            "nisServersOption",
            "nisDomainNameOption",
            "nisPlusServersOption",
            "nisPlusDomainNameOption",
            "sntpServersOption",
            "infoRefreshTimeOption",
            "genericOptions"
        })
        public static class Filters
            implements Serializable
        {

            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected List<OptionExpression> optionExpressions;
            protected Boolean sendRequestedOptionsOnlyPolicy;
            protected List<Policy> genericPolicies;
            protected PreferenceOption preferenceOption;
            protected ServerUnicastOption serverUnicastOption;
            protected StatusCodeOption statusCodeOption;
            protected VendorInfoOption vendorInfoOption;
            protected DnsServersOption dnsServersOption;
            protected DomainSearchListOption domainSearchListOption;
            protected SipServerAddressesOption sipServerAddressesOption;
            protected SipServerDomainNamesOption sipServerDomainNamesOption;
            protected NisServersOption nisServersOption;
            protected NisDomainNameOption nisDomainNameOption;
            protected NisPlusServersOption nisPlusServersOption;
            protected NisPlusDomainNameOption nisPlusDomainNameOption;
            protected SntpServersOption sntpServersOption;
            protected InfoRefreshTimeOption infoRefreshTimeOption;
            protected List<Option> genericOptions;

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the optionExpressions property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the optionExpressions property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOptionExpressions().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OptionExpression }
             * 
             * 
             */
            public List<OptionExpression> getOptionExpressions() {
                if (optionExpressions == null) {
                    optionExpressions = new ArrayList<OptionExpression>();
                }
                return this.optionExpressions;
            }

            /**
             * Gets the value of the sendRequestedOptionsOnlyPolicy property.
             * 
             * @return
             *     possible object is
             *     {@link Boolean }
             *     
             */
            public Boolean isSendRequestedOptionsOnlyPolicy() {
                return sendRequestedOptionsOnlyPolicy;
            }

            /**
             * Sets the value of the sendRequestedOptionsOnlyPolicy property.
             * 
             * @param value
             *     allowed object is
             *     {@link Boolean }
             *     
             */
            public void setSendRequestedOptionsOnlyPolicy(Boolean value) {
                this.sendRequestedOptionsOnlyPolicy = value;
            }

            /**
             * Gets the value of the genericPolicies property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the genericPolicies property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGenericPolicies().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Policy }
             * 
             * 
             */
            public List<Policy> getGenericPolicies() {
                if (genericPolicies == null) {
                    genericPolicies = new ArrayList<Policy>();
                }
                return this.genericPolicies;
            }

            /**
             * Gets the value of the preferenceOption property.
             * 
             * @return
             *     possible object is
             *     {@link PreferenceOption }
             *     
             */
            public PreferenceOption getPreferenceOption() {
                return preferenceOption;
            }

            /**
             * Sets the value of the preferenceOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link PreferenceOption }
             *     
             */
            public void setPreferenceOption(PreferenceOption value) {
                this.preferenceOption = value;
            }

            /**
             * Gets the value of the serverUnicastOption property.
             * 
             * @return
             *     possible object is
             *     {@link ServerUnicastOption }
             *     
             */
            public ServerUnicastOption getServerUnicastOption() {
                return serverUnicastOption;
            }

            /**
             * Sets the value of the serverUnicastOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServerUnicastOption }
             *     
             */
            public void setServerUnicastOption(ServerUnicastOption value) {
                this.serverUnicastOption = value;
            }

            /**
             * Gets the value of the statusCodeOption property.
             * 
             * @return
             *     possible object is
             *     {@link StatusCodeOption }
             *     
             */
            public StatusCodeOption getStatusCodeOption() {
                return statusCodeOption;
            }

            /**
             * Sets the value of the statusCodeOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link StatusCodeOption }
             *     
             */
            public void setStatusCodeOption(StatusCodeOption value) {
                this.statusCodeOption = value;
            }

            /**
             * Gets the value of the vendorInfoOption property.
             * 
             * @return
             *     possible object is
             *     {@link VendorInfoOption }
             *     
             */
            public VendorInfoOption getVendorInfoOption() {
                return vendorInfoOption;
            }

            /**
             * Sets the value of the vendorInfoOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link VendorInfoOption }
             *     
             */
            public void setVendorInfoOption(VendorInfoOption value) {
                this.vendorInfoOption = value;
            }

            /**
             * Gets the value of the dnsServersOption property.
             * 
             * @return
             *     possible object is
             *     {@link DnsServersOption }
             *     
             */
            public DnsServersOption getDnsServersOption() {
                return dnsServersOption;
            }

            /**
             * Sets the value of the dnsServersOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link DnsServersOption }
             *     
             */
            public void setDnsServersOption(DnsServersOption value) {
                this.dnsServersOption = value;
            }

            /**
             * Gets the value of the domainSearchListOption property.
             * 
             * @return
             *     possible object is
             *     {@link DomainSearchListOption }
             *     
             */
            public DomainSearchListOption getDomainSearchListOption() {
                return domainSearchListOption;
            }

            /**
             * Sets the value of the domainSearchListOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link DomainSearchListOption }
             *     
             */
            public void setDomainSearchListOption(DomainSearchListOption value) {
                this.domainSearchListOption = value;
            }

            /**
             * Gets the value of the sipServerAddressesOption property.
             * 
             * @return
             *     possible object is
             *     {@link SipServerAddressesOption }
             *     
             */
            public SipServerAddressesOption getSipServerAddressesOption() {
                return sipServerAddressesOption;
            }

            /**
             * Sets the value of the sipServerAddressesOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link SipServerAddressesOption }
             *     
             */
            public void setSipServerAddressesOption(SipServerAddressesOption value) {
                this.sipServerAddressesOption = value;
            }

            /**
             * Gets the value of the sipServerDomainNamesOption property.
             * 
             * @return
             *     possible object is
             *     {@link SipServerDomainNamesOption }
             *     
             */
            public SipServerDomainNamesOption getSipServerDomainNamesOption() {
                return sipServerDomainNamesOption;
            }

            /**
             * Sets the value of the sipServerDomainNamesOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link SipServerDomainNamesOption }
             *     
             */
            public void setSipServerDomainNamesOption(SipServerDomainNamesOption value) {
                this.sipServerDomainNamesOption = value;
            }

            /**
             * Gets the value of the nisServersOption property.
             * 
             * @return
             *     possible object is
             *     {@link NisServersOption }
             *     
             */
            public NisServersOption getNisServersOption() {
                return nisServersOption;
            }

            /**
             * Sets the value of the nisServersOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link NisServersOption }
             *     
             */
            public void setNisServersOption(NisServersOption value) {
                this.nisServersOption = value;
            }

            /**
             * Gets the value of the nisDomainNameOption property.
             * 
             * @return
             *     possible object is
             *     {@link NisDomainNameOption }
             *     
             */
            public NisDomainNameOption getNisDomainNameOption() {
                return nisDomainNameOption;
            }

            /**
             * Sets the value of the nisDomainNameOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link NisDomainNameOption }
             *     
             */
            public void setNisDomainNameOption(NisDomainNameOption value) {
                this.nisDomainNameOption = value;
            }

            /**
             * Gets the value of the nisPlusServersOption property.
             * 
             * @return
             *     possible object is
             *     {@link NisPlusServersOption }
             *     
             */
            public NisPlusServersOption getNisPlusServersOption() {
                return nisPlusServersOption;
            }

            /**
             * Sets the value of the nisPlusServersOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link NisPlusServersOption }
             *     
             */
            public void setNisPlusServersOption(NisPlusServersOption value) {
                this.nisPlusServersOption = value;
            }

            /**
             * Gets the value of the nisPlusDomainNameOption property.
             * 
             * @return
             *     possible object is
             *     {@link NisPlusDomainNameOption }
             *     
             */
            public NisPlusDomainNameOption getNisPlusDomainNameOption() {
                return nisPlusDomainNameOption;
            }

            /**
             * Sets the value of the nisPlusDomainNameOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link NisPlusDomainNameOption }
             *     
             */
            public void setNisPlusDomainNameOption(NisPlusDomainNameOption value) {
                this.nisPlusDomainNameOption = value;
            }

            /**
             * Gets the value of the sntpServersOption property.
             * 
             * @return
             *     possible object is
             *     {@link SntpServersOption }
             *     
             */
            public SntpServersOption getSntpServersOption() {
                return sntpServersOption;
            }

            /**
             * Sets the value of the sntpServersOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link SntpServersOption }
             *     
             */
            public void setSntpServersOption(SntpServersOption value) {
                this.sntpServersOption = value;
            }

            /**
             * Gets the value of the infoRefreshTimeOption property.
             * 
             * @return
             *     possible object is
             *     {@link InfoRefreshTimeOption }
             *     
             */
            public InfoRefreshTimeOption getInfoRefreshTimeOption() {
                return infoRefreshTimeOption;
            }

            /**
             * Sets the value of the infoRefreshTimeOption property.
             * 
             * @param value
             *     allowed object is
             *     {@link InfoRefreshTimeOption }
             *     
             */
            public void setInfoRefreshTimeOption(InfoRefreshTimeOption value) {
                this.infoRefreshTimeOption = value;
            }

            /**
             * Gets the value of the genericOptions property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the genericOptions property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getGenericOptions().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Option }
             * 
             * 
             */
            public List<Option> getGenericOptions() {
                if (genericOptions == null) {
                    genericOptions = new ArrayList<Option>();
                }
                return this.genericOptions;
            }

        }

    }

}
