//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.06 at 11:28:50 PM EDT 
//


package com.agr.dhcpv6.server.config.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.agr.dhcpv6.server.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.agr.dhcpv6.server.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DhcpV6ServerConfig.Links }
     * 
     */
    public DhcpV6ServerConfig.Links createDhcpV6ServerConfigLinks() {
        return new DhcpV6ServerConfig.Links();
    }

    /**
     * Create an instance of {@link DhcpV6ServerConfig.Filters }
     * 
     */
    public DhcpV6ServerConfig.Filters createDhcpV6ServerConfigFilters() {
        return new DhcpV6ServerConfig.Filters();
    }

    /**
     * Create an instance of {@link NisServersOption }
     * 
     */
    public NisServersOption createNisServersOption() {
        return new NisServersOption();
    }

    /**
     * Create an instance of {@link OpaqueData }
     * 
     */
    public OpaqueData createOpaqueData() {
        return new OpaqueData();
    }

    /**
     * Create an instance of {@link NisPlusServersOption }
     * 
     */
    public NisPlusServersOption createNisPlusServersOption() {
        return new NisPlusServersOption();
    }

    /**
     * Create an instance of {@link Policy }
     * 
     */
    public Policy createPolicy() {
        return new Policy();
    }

    /**
     * Create an instance of {@link OptionExpression }
     * 
     */
    public OptionExpression createOptionExpression() {
        return new OptionExpression();
    }

    /**
     * Create an instance of {@link DomainSearchListOption }
     * 
     */
    public DomainSearchListOption createDomainSearchListOption() {
        return new DomainSearchListOption();
    }

    /**
     * Create an instance of {@link VendorClassOption }
     * 
     */
    public VendorClassOption createVendorClassOption() {
        return new VendorClassOption();
    }

    /**
     * Create an instance of {@link PreferenceOption }
     * 
     */
    public PreferenceOption createPreferenceOption() {
        return new PreferenceOption();
    }

    /**
     * Create an instance of {@link ElapsedTimeOption }
     * 
     */
    public ElapsedTimeOption createElapsedTimeOption() {
        return new ElapsedTimeOption();
    }

    /**
     * Create an instance of {@link OptionRequestOption }
     * 
     */
    public OptionRequestOption createOptionRequestOption() {
        return new OptionRequestOption();
    }

    /**
     * Create an instance of {@link DnsServersOption }
     * 
     */
    public DnsServersOption createDnsServersOption() {
        return new DnsServersOption();
    }

    /**
     * Create an instance of {@link SipServerDomainNamesOption }
     * 
     */
    public SipServerDomainNamesOption createSipServerDomainNamesOption() {
        return new SipServerDomainNamesOption();
    }

    /**
     * Create an instance of {@link DhcpV6ServerConfig.Links.Filters }
     * 
     */
    public DhcpV6ServerConfig.Links.Filters createDhcpV6ServerConfigLinksFilters() {
        return new DhcpV6ServerConfig.Links.Filters();
    }

    /**
     * Create an instance of {@link DhcpV6ServerConfig }
     * 
     */
    public DhcpV6ServerConfig createDhcpV6ServerConfig() {
        return new DhcpV6ServerConfig();
    }

    /**
     * Create an instance of {@link NisPlusDomainNameOption }
     * 
     */
    public NisPlusDomainNameOption createNisPlusDomainNameOption() {
        return new NisPlusDomainNameOption();
    }

    /**
     * Create an instance of {@link SipServerAddressesOption }
     * 
     */
    public SipServerAddressesOption createSipServerAddressesOption() {
        return new SipServerAddressesOption();
    }

    /**
     * Create an instance of {@link ServerIdOption }
     * 
     */
    public ServerIdOption createServerIdOption() {
        return new ServerIdOption();
    }

    /**
     * Create an instance of {@link NisDomainNameOption }
     * 
     */
    public NisDomainNameOption createNisDomainNameOption() {
        return new NisDomainNameOption();
    }

    /**
     * Create an instance of {@link ClientIdOption }
     * 
     */
    public ClientIdOption createClientIdOption() {
        return new ClientIdOption();
    }

    /**
     * Create an instance of {@link InterfaceIdOption }
     * 
     */
    public InterfaceIdOption createInterfaceIdOption() {
        return new InterfaceIdOption();
    }

    /**
     * Create an instance of {@link UserClassOption }
     * 
     */
    public UserClassOption createUserClassOption() {
        return new UserClassOption();
    }

    /**
     * Create an instance of {@link VendorInfoOption }
     * 
     */
    public VendorInfoOption createVendorInfoOption() {
        return new VendorInfoOption();
    }

    /**
     * Create an instance of {@link SntpServersOption }
     * 
     */
    public SntpServersOption createSntpServersOption() {
        return new SntpServersOption();
    }

    /**
     * Create an instance of {@link InfoRefreshTimeOption }
     * 
     */
    public InfoRefreshTimeOption createInfoRefreshTimeOption() {
        return new InfoRefreshTimeOption();
    }

    /**
     * Create an instance of {@link ServerUnicastOption }
     * 
     */
    public ServerUnicastOption createServerUnicastOption() {
        return new ServerUnicastOption();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link StatusCodeOption }
     * 
     */
    public StatusCodeOption createStatusCodeOption() {
        return new StatusCodeOption();
    }

}
