=== DHCP Options
DHCP options are configured using the `options` element. Each option is specified by 
an element with a name of the option, for example `dnsServersOption`. The Jagornet 
DHCP server has pre-defined option definitions for the most common DHCPv4 and DHCPv6
options.  Other options are easily defined and supported.  See <<Generic Options>>
for details.

==== DHCPv4 Server Identifier Option
The Server Identifier Option is required by the DHCPv4 protocol for the server to 
include in reply packets. The identifier is an IPv4 address which DHCPv4 clients 
will send unicast requests to. The `v4ServerIdOption` must be specified in the 
`config/dhcpserver.xml` file. The default `config/dhcpserver.xml` file supplied with 
the Jagornet DHCP server specifies an empty DHCPv4 server identifier option as 
follows:

 <?xml version="1.0" encoding="UTF-8"?>
 <dhc:dhcpServerConfig xmlns:dhc="http://jagornet.com/dhcp/xml">
     <v4ServerIdOption/>
 </dhc:dhcpServerConfig>
 
Using this default configuration, the default IP address of the host will be set 
for the DHCPv4 server identifier by the Jagornet DHCP server upon initial startup. 
This will cause the `config/dhcpserver.xml` file to be rewritten with the populated 
`v4ServerIdOption`, for example:

 <?xml version="1.0" encoding="UTF-8"?>
 <dhc:dhcpServerConfig xmlns:dhc="http://jagornet.com/dhcp/xml">
   <v4ServerIdOption>
     <ipAddress>10.10.10.10</ipAddress>
   </v4ServerIdOption>
 </dhc:dhcpServerConfig>
 
This is the recommended way to create a server identifier. Optionally, the 
`v4ServerIdOption` can be specified using the ipAddress element, for example:

 <?xml version="1.0" encoding="UTF-8"?>
 <dhc:dhcpServerConfig xmlns:dhc="http://jagornet.com/dhcp/xml">
     <v4ServerIdOption>
         <ipAddress>11.11.11.11<ipAddress>
     </v4ServerIdOption>
 </dhc:dhcpServerConfig>

Whichever method is chosen to create the server identifier, it should not be 
changed once it has been created because this address will be used by clients 
when renewing their lease.

==== DHCPv6 Server Identifier Option
The Server Identifier Option is required by the DHCPv6 protocol for the server to 
include in reply packets. The `v6ServerIdOption` must be specified in the 
`config/dhcpserver.xml file`. The default `config/dhcpserver.xml` file supplied 
with the Jagornet DHCP server specifies an empty DHCPv6 server identifier option as 
follows:

 <?xml version="1.0" encoding="UTF-8"?>
 <dhc:dhcpServerConfig xmlns:dhc="http://jagornet.com/dhcp/xml">
     <v6ServerIdOption/>
 </dhc:dhcpServerConfig>
 
Using this default configuration, a DUID-LLT, as defined by section 9.2 of RFC 3315,
will be automatically generated by the Jagornet DHCP server upon initial startup. 
This will cause the `config/dhcpserver.xml` file to be rewritten with the generated 
`serverIdOption`, for example:

 <?xml version="1.0" encoding="UTF-8"?>
 <dhc:dhcpServerConfig xmlns:dhc="http://jagornet.com/dhcp/xml">
   <v6ServerIdOption>
     <opaqueData>
         <hexValue>0001000149EFC509001E52C94D49</hexValue>
     </opaqueData>
   </v6ServerIdOption>
 </dhc:dhcpServerConfig>
 
This is the recommended way to create a server identifier. Optionally, the 
`v6ServerIdOption` can be specified using the asciiValue of an opaque data option 
type, for example:

 <?xml version="1.0" encoding="UTF-8"?>
 <dhc:dhcpServerConfig xmlns:dhc="http://jagornet.com/dhcp/xml">
     <v6ServerIdOption>
         <opaqueData>
             <asciiValue>Jagornet-DHCP-Server</asciiValue>
         </opaqueData>
     </v6ServerIdOption>
 </dhc:dhcpServerConfig>
 
Whichever method is chosen to create the server identifier, it should not be 
changed once it has been created.

==== Configuration Options
Configuration Options are those options that can be configured for the server to 
return to clients in reply messages. For example, most network clients will need 
to know the address of one or more Domain Name System (DNS) servers.

include::options/dhcpv4_options.adoc[]
 
include::options/dhcpv6_options.adoc[]

include::options/generic_options.adoc[]

