# This is a basic workflow that is manually triggered

name: Version workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release:
        # Friendly description to be shown in the UI instead of 'release'
        description: 'Release to test'
        # Default value if no value is explicitly provided
        default: '4.0.1'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'adopt'
        # cache requires pom.xml
        #cache: maven
    # Runs a command using the runners shell
    - name: Download release
      run: wget "https://github.com/jagornet/dhcp/releases/download/${{ inputs.release }}/jagornet-dhcp-dist-${{ inputs.release }}-all.tar.gz"
    - name: Unpack the release package
      run: tar xvf "jagornet-dhcp-dist-${{ inputs.release }}-all.tar.gz"
    - name: Test the server version
      run: "jagornet-dhcp-dist-${{ inputs.release }}/bin/dhcpserver version 2>&1 |grep ${{ inputs.release}}"
        
